#pragma once
namespace fulgurdb {
enum ReturnStatus {
  FULGUR_SUCCESS = 0,
  FULGUR_BLOCK_FULL,
  FULGUR_END_OF_TABLE,
  FULGUR_INVALID_RECORD_LOCATION,
  FULGUR_TRANSACTION_ABORT,
  FULGUR_INVISIBLE_VERSION,
  FULGUR_FAIL,
  FULGUR_ABORT,
  FULGUR_RETRY,
  FULGUR_KEY_EXIST
};

}
