#pragma once
namespace db20xx {
enum ReturnStatus {
  FULGUR_SUCCESS = 0,
  FULGUR_BLOCK_FULL = 1,
  FULGUR_END_OF_TABLE = 2,
  FULGUR_INVALID_RECORD_LOCATION = 3,
  FULGUR_TRANSACTION_ABORT = 4,
  FULGUR_INVISIBLE_VERSION = 5,
  FULGUR_DELETED_VERSION = 6,
  FULGUR_FAIL = 7,
  FULGUR_ABORT = 8,
  FULGUR_RETRY = 9,
  FULGUR_KEY_EXIST = 10,
  FULGUR_KEY_NOT_EXIST = 11,
  FULGUR_INDEX_RANGE_END = 12
};

}
